---
title: "Pumpkins Dataset Output 🎃"
description: "This document contains all the results from and code used to complete the 'Pumpkins' portion of the LIFE4138 Coursework."
author: "Tahir Ansari"
date: "12 November 2025"
format:
    html:
        toc: true
        toc-title: "Contents"
        embed-resources: true
        page-layout: full
        theme: united
        title-block-banner: true
        smooth-scroll: true
        number-sections: true
---

```{=html}
<style>
  body { background-color: #FFF4E6; }
</style>
```

## Task 1 - Read in the dataset 🔍 {#Task-1}
The first task involved reading in the `pumpkins.csv` file. To do this the following `import_dataset` function was made. It returns a dataframe only if the file can be found, is not empty and opens correctly. It quits the program if it fails to prevent unneccesary errors or empty graphs from being created.

### Importing Data
```{python}
#| echo: true
#| code-fold: true
#| code-summary: "Show the import_dataset code"
import pandas as pd

def import_dataset(path :str)-> pd.DataFrame: 
    '''
    Function to import a csv dataset from its filepath or url
    Checks to see if 
    Arguments:
    path: Takes a string of a url or filepath of a csv file to import.

    Returns:
    dataset - returns a pandas dataframe
    '''
    if path.lower().endswith('.csv') == False: #Error if not .csv file
        print("File is not a csv file")
        quit() #Prevents script running if not valid file
    try:
        dataset = pd.read_csv(path) #Imports the dataset
        print('Dataset imported successfully!')
        return dataset
    except FileNotFoundError: #Error if file doesnt exist
        print("File not found, please enter a valid path")
        quit() #Prevents script running if not valid file
    except pd.errors.EmptyDataError: #Error if file empty
        print("The provided file is empty.")
        quit() #Prevents script running if not valid file
    except pd.errors.ParserError: #Error if not in csv format inside
        print("Please check if this in .csv format") #Prevents script running if not valid file
    except Exception as e: #Any other error
        print(f"Unknown error: {e}")
        quit() #Prevents script running if not valid file
    return None
```
This could then be called using the filepath of the .csv file. It is assigned here to the variable `pumpkins` for ease of use later.
```{python}
#| echo: true
pumpkins = import_dataset('pumpkins_datasets/pumpkins_02.csv')
```

### Checking Data Validity
While the previous function checks if the .csv file is completely empty, the data was checked on whether it contained all the columns needed for the analysis. Those columns were then checked to see if they were empty. For this the following function was used:
```{python}
#| echo: true
#| code-fold: true
#| code-summary: "Show the check_empty code"
def check_empty(dataframe: pd.DataFrame):
    '''
    Function to check if any of the columns used are completely empty and stops the program.
    Empty columns will cause errors in the graphs, so stops code running unnecesarily.
    '''
    required_cols = [
        "weight_lbs",
        "est_weight",
        "country",
        "variety",
        "city",
        "state_prov",
        "id"
    ]
    missing_cols = []
    empty_cols = []

    for col in required_cols:
        if col not in dataframe.columns:
            missing_cols.append(col)
        elif dataframe[col].isna().all() or len(dataframe[col]) == 0:
            empty_cols.append(col)
    
    if len(missing_cols) > 0 or len(empty_cols) > 0:
        raise KeyError(f"Missing required columns: {missing_cols}\nEmpty columns: {empty_cols}")
        quit()
    return None
```
This function also quits the script if it fails, to prevent errors further on. It was then called as below:
```{python}
#| echo: true
check_empty(pumpkins)
```

## Task 2 - Identifying the heaviest pumpkin ⚖️ {#Task-2}
Next was to identify the heaviest pumpkin and data about it including: weight, variety, where it was from and when it was grown.

To do this the `find_highest` function was created to get the row with a highest value in a specific column.

The code for this function can be seen here:
```{python}
#| echo: true
def find_highest(dataframe: pd.DataFrame,column: str):
    '''
    Function to get the row information of the highest value in a column

    Arguments:
    dataframe: the dataframe to search through
    column: the column to search through for the highest value
    '''
    if (isinstance(dataframe, pd.DataFrame)) == False:
        print(f"First argument must be a pandas dataframe")
        return None
    try:
        highest_row = dataframe.loc[dataframe[column].idxmax()]
        return highest_row
    except KeyError:
        print(f"{column} does not exist in the dataframe")
    except NameError:
        print('Please provide a valid variable')
    except AttributeError:
        print('Please enter a valid argument type')
    return None
```
This function was called and we can see general information about the pumpkin below.
```{python}
#| echo: true
heaviest_pumpkin = find_highest(pumpkins,'weight_lbs')
print(f"The heaviest pumpkin was a {heaviest_pumpkin['variety']} from {heaviest_pumpkin['city']}, {heaviest_pumpkin['state_prov']}, {heaviest_pumpkin['country']}.\nIt weighed {round(heaviest_pumpkin['weight_lbs'],2)}lbs and was grown in the year {heaviest_pumpkin['id'].removesuffix('-P')}.")
```
## Task 3 - Conversion and Creation 📏 {#Task-3}
### Converting pounds to kilograms
The function `lbs_to_kg` was created to convert a value in lbs to kg, allowing it to be applied on mass in the next part.
```{python}
#| echo: true
def lbs_to_kg(value: float|int) -> float:
    '''
    Function to convert a value in lbs to kg
    Takes a column input of values in lbs

    Arguments:
    value: a value to be converted

    Returns: new value as a float
    '''
    try:
        return ((float(value))/2.20462) #return converted value
    except ValueError: #Error if not a number
        print("Please enter a valid number")
        return None
    except TypeError: #Error if no value provided
        print("Please pass a number into the function")
        return None

```
We can test this works using known values of lbs and kgs. For example, 2.20462 lbs is equal to 1kg and running the function should return `1.0`.
```{python}
#| echo: true
lbs_to_kg(2.20462)
```
### Creating a new column
Now that this function is verified to work it can be used to create new column of weight in kilograms.

The following line of code was ran that created a new column and called the previously created function
```{python}
#| echo: true
pumpkins[f"weight_in_kg"] = [(lbs_to_kg(i)) for i in pumpkins['weight_lbs']] #Creates new column using values by calling conversion function in list
```
Now we can take a look at the new column in the dataset:
```{python}
#| echo: true
print(pumpkins.head(1))
```
We can re-run the code from earlier on the new column to find the value in kg for the heaviest pumpkin
```{python}
#|echo: true
heaviest_pumpkin = find_highest(pumpkins,'weight_in_kg')
print(f"The heaviest pumpkin was a {heaviest_pumpkin['variety']} from {heaviest_pumpkin['city']}, {heaviest_pumpkin['state_prov']}, {heaviest_pumpkin['country']}.\nIt weighed {round(heaviest_pumpkin['weight_in_kg'],2)}kg and was grown in the year {heaviest_pumpkin['id'].removesuffix('-P')}.")
```
## Task 4 - Weight class 🏋🏼‍♂️ {#Task-4}
This task required creating another new column, with three classes of weight: light, medium and heavy.

The thresholds decided for these were as follows:

| Threshold | Weight (kg) |
|-----------|-------------|
| light     | <250        |
| medium    | 250-500     |
| heavy     | >500        |


This column was created using the following code.
```{python}
#| echo: true
classes = []
for i in pumpkins['weight_in_kg']:
    if i<250: #Light weight class if weight <250
        classes.append('light')
    elif i<500: #Medium weight class if weight >250 but <500
        classes.append('medium')
    else:#Heavy weight class if weight >500
        classes.append('heavy')
pumpkins["weight_class"] = classes #Create new column from classes list
```
We can see the `weight_class` values for the first three rows below
```{python}
#| echo: true
print(pumpkins[['weight_in_kg','weight_class']].head(3))   
```

## Task 5 - Estimated vs Actual Weight plotting 📈 {#Task-5}
### Standardising Units
Next was to create a plot of the estimated weight of the pumpkins against the actual weights.

This can be done in a number of ways but the important thing to note is that both axis require the same units. One could plot the `est_weight` against the `weight` in lbs using the data already available in the dataset, but to make use of the function created in [task 3](#Task-3), the values were plotted in kilograms.

A new column in the dataset was created called `est_weight_kg` using the code below.
```{python}
#| echo: true
pumpkins[f"est_weight_kg"] = [(lbs_to_kg(i)) for i in pumpkins['est_weight']]
```
This new set column of data (`est_weight_kg`) can be plotted against the `weight_in_kg` column to see the relationship.

### Creating the graph
The module matplotlib is used to create graphs and is imported.
```{python}
#| echo: true
import matplotlib.pyplot as plt
```
Next a plot of the two columns can be created. 

Note: The `sns` module was used here to aid in colouring.

::: {layout-ncol=1}

```{python}
#| echo: true
#| label: fig-estimated_vs_actual
#| fig-cap: A Scatterplot of the relationship between the estimated weight and the actual weight, in kilograms, of pumpkins from the pumpkin competitions dataset. The different colours of plot represent the weight class of each point.

import seaborn as sns

figure_1 = sns.scatterplot(data = pumpkins, x = 'est_weight_kg', y = 'weight_in_kg', hue = 'weight_class', palette='colorblind') #Creates a new figure to draw graph on
figure_1.figure.set_size_inches(10,5)
figure_1.figure.tight_layout(rect=[0, 0.05, 0.85, 0.95]) #Creates whitespace at top and bottom of graph
figure_1.set_title('Estimated Pumpkin Weight vs Actual Pumpkin Weight') #Adding title and axis labels
figure_1.legend(title = 'Weight Class', bbox_to_anchor=(1.02, 1), loc=2, borderaxespad=0.)
figure_1.set_xlabel('Estimated Weight (kg)') #Adding x axis label
figure_1.set_ylabel('Actual Weight (kg)'); #Adding y axis label
figure_1.figure.text(
0.5, #Adjusts caption
0.02, #adjusts caption
"A Scatterplot of the relationship between the estimated weight and the actual weight, in kilograms, of pumpkins from the pumpkin competitions dataset. \nThe different colours of plot represent the weight class of each point.", 
ha = 'center', 
fontsize = 9);
```
The pattern observed should be the same as if the estimated and actual weight values were plotted in lbs, which can be seen below.
```{python}
#| echo: true
#| code-fold: true
#| label: fig-estimated_vs_actual_lbs
#| fig-cap: A Scatterplot of the relationship between the estimated weight and the actual weight, in lbs, of pumpkins from the pumpkin competitions dataset.
figure_2 = plt.figure() #Creates a second figure to draw graph on
plot_area_2 = figure_2.add_subplot() #Creates a new plotting area inside figure_2 to make axes
plot_area_2.scatter(x = pumpkins['est_weight'],y = pumpkins['weight_lbs'],alpha = 0.25, color = 'darkorange') #Creating the graph in lbs for checking
plot_area_2.set_title('Estimated Pumpkin Weight vs Actual Pumpkin Weight') #Adding title
plot_area_2.set_xlabel('Estimated Weight (lbs)') #Adding x axis label
plot_area_2.set_ylabel('Actual Weight (lbs)'); #Adding y axis label
#figure_2.show() - This line is commented as it does not function corectly in markdown
```

:::

As can be seen above, the two graphs have identical patterns, meaning there were no issues when converting to kilograms.

### Saving the graph
Next we can save this graph as a file by running the following code, this also creates a nice outputs folder for the graphs if it doesn't exist.
```{python}
#| echo: true
import os
os.makedirs("outputs", exist_ok=True)

figure_1.figure.savefig("outputs/pumpkins_weight_relationship.png", dpi = 300) #Saves the first figure to disk. Increased DPI to improve readability.
```

### What does the scatterplot show?

As seen in @fig-estimated_vs_actual there is a strong positive relationship between the estimated and actual weight. 

There are many outliers such as the large cluster at Estimated Weight = 0, this is most likely due to there not being an estimated weight value for these entries. 

As the estimated weight increases beyond ~800kg, the spread of the points show that weight was less reliably estimated.

## Task 6 - Selecting three countries 🇬🇧 🇯🇵 🇮🇹 {#Task-6}

The three countries chosen for this exercise were the United Kingdom, Japan and Italy.

### Filtering the data

Firstly, a subset of the dataset was created by checking if the country value was in a predefined list.
```{python}
#| echo: true
filter_vars = [country in ['United Kingdom', 'Japan', 'Italy'] for country in pumpkins['country']] #Checks if country in list, creates list of true and false values

filtered_pumpkins = pumpkins[filter_vars] #Creates list by adding the row if filter_vars returns True
```

### Saving the filtered data
The filtered data can be easily saved to disk using:
```{python}
#| echo: true
filtered_pumpkins.to_csv('outputs/pumpkins_filtered.csv')
```

## Task 7 - Summarising the filtered data 🧮 {#Task-7}
Next was to summarise the filtered data, with two key tasks. Finding the mean weight per country and finding the mean weight for each variety per country.
This exercise was done using the previously calculated kilogram values.

### Finding mean weight per country
This was done by grouping the `filtered_pumpkins` dataframe by `country` and then selecting the `weight_in_kg` column and calculating the mean.
The mean values for each country can be seen below.
```{python}
#| echo: true
print(f"Mean pumpkin weight per country: \n{filtered_pumpkins.groupby('country')['weight_in_kg'].mean()}") #Groups by country and 
#filters to only weight and calculates mean
```

### Finding mean weight per variety per country
```{python}
#| echo: true
mean_variety_country = filtered_pumpkins.groupby(['country','variety'])['weight_in_kg'].mean()
print(f"Mean weights of pumpkin by variety and country: \n {mean_variety_country}") #Groups by country and calculates mean value and then prints
```

Next to get the lowest mean weight variety we can do:
```{python}
#| echo: true
lowest_mean_row = mean_variety_country.idxmin() #Gets lowest row (country, variety)
lowest_mean_value = mean_variety_country.min() #Gets lowest mean weight value
print(f"The lowest mean weight was '{lowest_mean_row[1]}' from {lowest_mean_row[0]}, weighing {round(lowest_mean_value,2)}kg.")
```

## Task 8 - Weight Distribution Boxplot 📊  {#Task-8}

### Creating a boxplot
::: {layout-ncol=1}
```{python}
#| echo: true
#| label: fig-weight_boxplot
#| fig-cap: A boxplot showing the distribution of pumpkin weight across Italy, Japan and the United Kingdom from the filtered pumpkin competitions dataset. Italy has the highest median pumpkin weight, with Japan having lowest median and spread of data and the United Kingdom has an intermediate distribution.
figure_3 = plt.figure(figsize=(10,6)) #Creates a new figure
plot_area_3 = figure_3.add_subplot() #Creates new plotting area in figure
filtered_pumpkins.boxplot(column = 'weight_in_kg', by = 'country', ax = plot_area_3)
plt.suptitle("") #Removes pandas title so I can add my own
figure_3.subplots_adjust(bottom=0.18)
plot_area_3.set_title("Boxplot of Weight distribution by country")
plot_area_3.set_xlabel('Country')
plot_area_3.set_ylabel('Pumpkin Weight (kg)')
figure_3.text(
    0.5,
    0.02,
    "A boxplot showing the distribution of pumpkin weight across Italy, Japan and the United Kingdom from the filtered pumpkin competitions dataset. \nItaly has the highest median pumpkin weight, with Japan having lowest median and spread of data and the United Kingdom has an intermediate distribution.", 
    ha = 'center', 
    fontsize = 9);
```
:::

### Saving the boxplot
This boxplot can now be saved by running:
```{python}
#| echo: true
figure_3.savefig("outputs/filtered_boxplot.png", dpi = 300) #Saves the third figure (boxplot) to disk. Increased dpi to improve readability.
```

### What does the boxplot show?
In @fig-weight_boxplot the distribution of pumpkin weight in kg of the three countries (United Kingdom, Japan and Italy) can be seen. 

Looking at the three boxes, it is seen that Italy produced the heighest overall weighted pumpkins, as its median is higher than both Japan and the United Kingdom.
Italy also has a large number of outliers

Japan produces the lowest weighted pumpkins as its median is below both of the other countries. It also has the lowest interquartile range of the countries, showing
low variability. Japan also has the least number of outliers.

The United Kingdom produces pumpkins weighted in between the other countries based on its median value. It has a similar number of outliers to Italy but at lower weights.

## Task 9 - Facet Plot 📉 {#Task-9}

### Creating the facet plot
To create a facet plot from the plot in Task 8, the seaborn module was imported and used.
```{python}
#| echo: true
import seaborn as sns
```

Next a facet plot can be made using seaborn as follows:
```{python}
#| echo: true
#| label: fig-facet_boxplot
#| fig-cap: A boxplot showing distribution of pumpkin weight by variety and country from the filtered pumpkin competitions dataset.
#| column: screen-inset
facetplot = sns.catplot( #have to use catplot as boxplot has no facetting
        data = filtered_pumpkins, #Chooses filtered dataset
        x = 'variety', #Chooses axis for data
        y = 'weight_in_kg', #Chooses axis for data
        col = 'country',
        kind = 'box',
        hue = 'variety', #Creates coloured subplots based on variety
        palette = 'colorblind' #Changes palette to be *colourblind friendly*
    )
facetplot.set_xticklabels(rotation=90)
facetplot.figure.set_size_inches(17.5,8)
facetplot.figure.tight_layout(rect=[0, 0.05, 1, 0.95]) #Creates whitespace at top and bottom of graph
facetplot.set_axis_labels("Variety","Pumpkin Weight (kg)") #Names x and y axis
facetplot.figure.suptitle("Boxplot of Pumpkin Weight by Variety and Country", y=0.98) #Adds main figure title
facetplot.set_titles("{col_name}") #Gives each sub plot title
facetplot.figure.text(
    0.5, #Adjusts caption
    0.02, #adjusts caption
    "A boxplot showing distribution of pumpkin weight by variety and country from the filtered pumpkin competitions dataset.", 
    ha = 'center', 
    fontsize = 9);
```

### Saving the plot
This facet boxplot can now be saved by running:
```{python}
#| echo: true
facetplot.figure.savefig("outputs/filtered_facet_boxplot.png",bbox_inches='tight', dpi = 300) #Saves facetplot to disk. to disk. Increased dpi to improve readability.
#bbox_inches reduces whitespace making it easier to read
```

### What does the facet boxplot show?
@fig-facet_boxplot shows a similar pattern to @fig-weight_boxplot, but with greater breakdown of the varieties contributing to the patterns observed previously.
It still shows a similar pattern of Japan being, generally, the lowest median weight for pumpkins, followed by the United Kingdom and Italy.